const JOBS=[
{id:'94c2b175',team:'Chatcut',pos:'海外AI内容运营实习生',loc:'上海',locD:'上海',dept:'operations',c:'#1a1a1a',ic:'C',tags:['实习','上海'],website:'https://chatcut.io',type:'实习',desc:`<h3>工作职责</h3><ul><li>关注YouTube、TikTok等海外社交媒体平台内容趋势，挖掘热门视频风格与视觉玩法，策划高质量视频风格、动态图形等模板内容</li><li>日常深度使用产品进行创作，调优Prompt、复刻热点内容效果，对AI产出效果进行评测与迭代</li><li>结合产品能力与海外内容热点，独立完成从选题到内容上线的完整流程</li></ul>
<h3>任职要求</h3><ul><li>本科及以上学历在读，影视/设计/传播/创意相关专业优先</li><li>熟悉主流AI视频与图像生成工具，有Prompt调教经验</li><li>网感好，日常刷海外社媒，对视觉审美有自己的判断</li><li>自驱力强，能独立推进工作</li></ul>
<p><strong>实习要求：</strong>每周4天以上，至少3个月</p>`},
{id:'b3692451',team:'Cherry Studio',pos:'前端工程师',loc:'上海',locD:'上海',dept:'engineering',c:'#6c5ce7',ic:'C',tags:['全职','上海'],website:'https://cherrystudiochina.com',type:'全职',desc:`<h3>任职要求</h3><ul><li>深入理解和实践React、TypeScript、Node.js</li><li>熟练运用TailwindCSS、shadcn/ui等现代工具库</li></ul>`},
{id:'cd1414f8',team:'Cherry Studio',pos:'后端工程师',loc:'上海',locD:'上海',dept:'engineering',c:'#6c5ce7',ic:'C',tags:['全职','上海'],website:'https://cherrystudiochina.com',type:'全职',desc:`<h3>任职要求</h3><ul><li>熟练掌握Go与Node.js生态</li><li>具备高并发架构设计能力</li></ul>`},
{id:'924ab4b9',team:'Cherry Studio',pos:'全栈工程师',loc:'上海',locD:'上海',dept:'engineering',c:'#6c5ce7',ic:'C',tags:['全职','上海'],website:'https://cherrystudiochina.com',type:'全职',desc:`<h3>任职要求</h3><ul><li>深谙React、Node.js与Electron技术栈</li><li>能独立打造跨平台桌面客户端</li></ul>`},
{id:'6a67d62c',team:'Cherry Studio',pos:'移动端工程师',loc:'上海',locD:'上海',dept:'engineering',c:'#6c5ce7',ic:'C',tags:['全职','上海'],website:'https://cherrystudiochina.com',type:'全职',desc:`<h3>任职要求</h3><ul><li>熟练掌握React Native架构</li><li>兼具iOS或Android原生开发能力</li></ul>`},
{id:'ff8ea7e5',team:'Cherry Studio',pos:'测试工程师',loc:'上海',locD:'上海',dept:'engineering',c:'#6c5ce7',ic:'C',tags:['全职','上海'],website:'https://cherrystudiochina.com',type:'全职',desc:`<h3>任职要求</h3><ul><li>极度的耐心和细腻的用户视角</li><li>能定义AI Agent的测试标准，保障AI产品极致体验</li></ul>`},
{id:'bdc26dbb',team:'Evomap',pos:'全栈产品工程师',loc:'深圳',locD:'深圳',dept:'engineering',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责Console / Marketplace / Asset Detail / Dashboard / Ask相关前后端</li><li>实现节点状态、资产详情、贡献记录、收益预览、反馈入口</li><li>打通从「接入→发布→被复用→获得反馈/收益」的完整用户链路</li><li>优化高信息密度页面：搜索、筛选、排序、依赖关系、审计可视化</li></ul>
<h3>任职要求</h3><ul><li>TypeScript + React / Next.js 熟练</li><li>熟悉服务端渲染、缓存、鉴权、表单状态管理</li><li>熟悉图表、关系展示、复杂列表与高密度后台界面</li><li>能写必要Node/Python BFF或API层</li><li>了解事件埋点、漏斗分析、前端性能优化</li></ul>`},
{id:'9ce2c761',team:'Evomap',pos:'全栈AI视觉设计师',loc:'深圳',locD:'深圳',dept:'design',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>AI驱动的高品质视觉创意设计（营销海报、品牌视觉、UI/UX、社媒配图等）</li><li>训练和维护符合品牌规范的专属LoRA模型</li><li>搭建「传统设计+AIGC」高效工作流，扩充AI设计资产库</li><li>将AI设计方法论沉淀为教程或Agent能力，赋能团队</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，美术/视觉传达/设计类相关专业，2年以上商业视觉设计经验</li><li>精通Photoshop、Illustrator、Figma等传统设计工具</li><li>熟练使用Midjourney/Nano banana，熟悉ComfyUI/WebUI及ControlNet、LoRA等精准控图技术</li><li>对即梦、可灵、Runway、Sora等AI视频生成工具有实操经验</li></ul>
<h3>加分项</h3><ul><li>有C4D/Blender/Houdini或AE/PR动效能力</li><li>具备手绘插画、摄影或艺术创作背景</li></ul>`},
{id:'0f358abb',team:'Evomap',pos:'AI内容制作',loc:'深圳',locD:'深圳',dept:'operations',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责硬科技产品、技术解读、行业前沿分析等中短视频从0到1制作</li><li>全矩阵账号（B站、视频号、抖音、小红书及海外YouTube/X等）内容制作与分发</li><li>追踪核心指标（播放量、完播率、互动率）并持续优化内容策略</li><li>深度使用AI工具（Nano banana、Seedance2.0、kling等）提升生产效率</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，1-3年视频策划/剪辑或科技类媒体内容营销经验</li><li>对硬科技（AI、具身智能、芯片等）有狂热兴趣</li><li>精通剪映、Pr、AE、达芬奇等视频剪辑与特效软件</li></ul>
<h3>加分项</h3><ul><li>重度AI工具使用者，有AI辅助视频/图像/文本创作成功案例</li><li>拥有个人科技/AI/科普类自媒体账号</li><li>有海外广告/SEO经验</li><li>懂基础代码逻辑</li></ul>
<p><strong>申请须知：</strong>请附带过往独立制作的科技类或高质量视频作品链接集</p>`},
{id:'4ce8f546',team:'Evomap',pos:'AI新媒体品牌运营',loc:'深圳',locD:'深圳',dept:'operations',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>统筹公司全平台官方账号（双微一抖、小红书、知乎等），制定品牌传播策略</li><li>识别并接触高质量技术人才，放大公司AI/硬科技领域的影响力</li><li>策划组织技术分享、团建等活动，负责新员工Onboarding设计</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，1-3年新媒体运营、社区运营或科技互联网公司HR经验</li><li>性格开朗，沟通能力强，具备极强同理心</li><li>重度社交媒体网民，懂梗、会玩，具备基础图片排版和短视频审美</li><li>对AI、大模型、科技圈行业黑话有基本认知</li></ul>
<h3>加分项</h3><ul><li>有科技/AI创业公司从0到1团队搭建经历</li><li>自带科技媒体、高校圈子、开发者社区人脉资源</li></ul>`},
{id:'861fd20f',team:'Evomap',pos:'AI测开工程师',loc:'深圳',locD:'深圳',dept:'engineering',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>搭建LLM评估流水线：基于LLM-as-a-Judge对生成代码自动化打分</li><li>构建动态靶场：开发能随机改变DOM结构的测试诱饵网站</li><li>大模型回归测试：跑通历史失败Case，验证系统智商是否退化</li><li>沙箱攻防与越权测试：编写诱导大模型幻觉或生成恶意指令的极端用例</li></ul>
<h3>任职要求</h3><ul><li>熟练掌握Python，熟悉Pytest等测试框架</li><li>熟悉主流大模型API，能手写高质量Evaluation Prompt</li><li>精通Playwright/Puppeteer/Selenium</li><li>了解Docker/K8s基本原理</li></ul>`},
{id:'0ddf1cd9',team:'Evomap',pos:'AI红队测开工程师',loc:'深圳',locD:'深圳',dept:'engineering',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责平台及相关Agent/Capsule执行链路的对抗测试、异常注入与回归验证</li><li>设计自动化测试用例，覆盖网页变化、接口漂移、异常数据等场景</li><li>将自动化测试接入CI/CD流水线，建立发布质量闸门</li><li>验证沙箱隔离、限流熔断与故障恢复机制的有效性</li></ul>
<h3>任职要求</h3><ul><li>计算机相关专业本科及以上，3年以上测试开发/SDET/可靠性工程或安全测试经验</li><li>熟悉Python、Go、Node.js中至少一门</li><li>熟练使用Playwright、Selenium、Cypress等至少一种自动化测试框架</li><li>理解单元测试、集成测试、端到端测试、故障注入等方法</li></ul>
<h3>加分项</h3><ul><li>有红队测试、混沌工程、故障注入或沙箱隔离相关经验</li><li>有Agent、Browser Automation或AI Coding系统相关测试经验</li><li>有从0到1搭建自动化测试平台经验</li></ul>`},
{id:'75d95770',team:'Evomap',pos:'进化机制与经验抽象研究员',loc:'深圳',locD:'深圳',dept:'engineering',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>研究「经验如何从一次成功变成可复用的Gene/Capsule」</li><li>设计Gene/Capsule的能力分层与抽象准则</li><li>分析高价值资产的结构模式：步骤、依赖、约束、环境前提</li><li>研究资产组合与配方化的表达方式</li><li>与协议工程师一起把抽象落成schema和产物规范</li></ul>
<h3>核心研究问题</h3><ul><li>成功解法中哪些部分应抽象成Gene，哪些保留在Capsule</li><li>如何识别高价值「能力模式」而非一次性技巧</li><li>如何支持组合、继承、变体演化，不让资产碎片化</li><li>如何衡量经验传播带来的「网络增益」</li></ul>`},
{id:'0dfa59d8',team:'Evomap',pos:'AI产品平台资产审核',loc:'深圳',locD:'深圳',dept:'operations',c:'#e84855',ic:'E',tags:['全职','实习','深圳'],website:'https://evomap.ai',type:'全职',desc:`<h3>工作职责</h3><ul><li>对AI Agent发布的演化资产（Gene、Capsule等）进行抽样人工复核</li><li>监控并干预系统标记的异常资产，防范恶意Agent上传破坏性代码</li><li>负责Bounty/Swarm纠纷仲裁</li><li>配合研发团队持续优化平台自动化拦截规则</li></ul>
<h3>任职要求</h3><ul><li>大专及以上，1年以上互联网平台客服或技术支持经验，计算机相关专业优先</li><li>具备基础代码阅读能力（能看懂JSON、Python/Node.js基础代码及报错日志）</li><li>熟悉AI Agent、LLM运作原理，了解Prompt注入或代码安全漏洞者优先</li><li>逻辑严密，对数据异常敏感，具备极强责任心与技术合规意识</li></ul>`},
{id:'52970f79',team:'Floatboat',pos:'AI Native全栈开发（TypeScript方向）',loc:'北京',locD:'北京',dept:'engineering',c:'#3185fc',ic:'F',tags:['全职','北京'],website:'https://floatboat.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>优化客户端体验，用TypeScript封装AI推理逻辑为流畅的界面响应</li><li>探索大模型能力在前端交互中的最佳落地实践</li></ul>
<h3>任职要求</h3><ul><li>熟悉Python/Node.js/TypeScript/Go/Rust中任一语言，重点具备TypeScript能力</li><li>有机器学习或NLP领域实际项目经历或比赛经历</li><li>每周出勤5天（允许1天远程）</li></ul>
<h3>加分项</h3><ul><li>熟悉搜索引擎原理及相关优化</li><li>日Token消耗量200刀以上</li><li>拥有顶会/期刊论文（NeurIPS/ICML/ACL等）</li><li>有ACM参赛经历</li></ul>`},
{id:'733adaab',team:'Floatboat',pos:'Agent算法工程师',loc:'北京',locD:'北京',dept:'engineering',c:'#3185fc',ic:'F',tags:['全职','北京'],website:'https://floatboat.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>链路调优：精确定位从Prompt、检索、推理到生成的全链路效果问题</li><li>系统迭代：设计并实施自动化调优链路</li><li>核心打榜：追踪前沿大模型，主导核心业务能力的评测调优</li></ul>
<h3>任职要求</h3><ul><li>熟悉Python/Node.js/TypeScript/Go/Rust中任一语言，重点具备TypeScript能力</li><li>有机器学习或NLP领域实际项目经历</li><li>每周出勤5天（允许1天远程）</li></ul>
<h3>加分项</h3><ul><li>熟悉搜索引擎原理</li><li>日Token消耗量200刀以上</li><li>拥有顶会/期刊论文</li><li>在对话系统、信息检索方向有实际研发经验</li></ul>`},
{id:'0dc3d453',team:'Floatboat',pos:'Agent Harness Engineer（自动化测试）',loc:'北京',locD:'北京',dept:'engineering',c:'#3185fc',ic:'F',tags:['全职','北京'],website:'https://floatboat.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>设计并实现Agent评估框架（eval harness），覆盖端到端任务完成率、工具调用准确性等</li><li>构建可复现的测试用例集（benchmark suite）</li><li>开发自动化CI/CD管线中的Agent质量门禁</li><li>维护测试结果的可观测性平台，提供dashboard、告警和趋势分析</li></ul>
<h3>任职要求</h3><ul><li>3年以上自动化测试或测试基础设施开发经验</li><li>熟悉Python/TypeScript，能独立开发测试框架</li><li>了解LLM API调用模式（tool use、structured output、streaming）</li><li>有Playwright、Pytest、Jest等测试框架实战经验</li><li>熟悉CI/CD系统（GitHub Actions、GitLab CI等）</li></ul>
<h3>加分项</h3><ul><li>有AI Agent/Copilot类产品测试经验</li><li>了解eval-driven development（EDD）方法论</li><li>熟悉SWE-bench、HumanEval等Agent评估基准</li><li>有cost-aware testing经验</li></ul>`},
{id:'6606d870',team:'Humanify',pos:'大模型算法工程师',loc:'杭州',locD:'杭州',dept:'engineering',c:'#2ecc71',ic:'H',tags:['全职','实习','杭州'],website:null,type:'全职',desc:`<h3>工作职责</h3><ul><li>围绕推理pipeline、端到端模型、多模态任务、认知等前沿领域构建模型</li><li>设计数据方案，提取、清洗、生成高质量数据用于模型scaling</li><li>对大模型进行Post-Training，提升任务表现</li><li>与工程成员协作完成模型能力集成</li></ul>
<h3>任职要求</h3><ul><li>硕士及以上学历，计算机、数学等相关专业</li><li>熟悉Prompt、SFT、RLHF、Agent RL等大模型训练技术</li><li>熟练掌握PyTorch、TensorFlow等深度学习框架</li><li>有多卡/分布式训练、多模态LLM项目实战经验</li></ul>
<h3>加分项</h3><ul><li>在计算机科学高水平会议/期刊发表论文或有竞赛经验</li></ul>`},
{id:'0db57e3e',team:'Humanify',pos:'开发者社区运营（Developer Relations）',loc:'杭州',locD:'杭州',dept:'operations',c:'#2ecc71',ic:'H',tags:['全职','实习','杭州'],website:null,type:'全职',desc:`<h3>工作职责</h3><ul><li>建设Humanify开发者社区，深度参与AI Agent/OpenClaw/LLMOps/Vibe Coding等开发者生态</li><li>与开发者共建插件、模板、demo和工具</li><li>通过Tutorial、Docs、Demo、Hackathon、Meetup等帮助开发者上手Humanify OS</li><li>将社区反馈带回产品与技术团队</li></ul>
<h3>任职要求</h3><ul><li>英语native或接近母语水平（必须）</li><li>对AI开发者生态高度敏感，持续使用各种新工具</li><li>熟悉GitHub、Twitter/X、Discord、Reddit、Hacker News等开发者社区</li><li>有清晰的表达能力，能把复杂技术讲清楚</li></ul>
<h3>加分项</h3><ul><li>有DevRel/Developer Community/Technical Evangelist经验</li><li>有AI Agent/LLM/AI开发工具相关经验</li><li>有技术博客、开源项目或技术社交媒体影响力</li><li>有Hackathon/Meetup/Developer Event组织经验</li></ul>`},
{id:'f0205bf9',team:'InsForge',pos:'社媒社区运营实习生',loc:'深圳',locD:'深圳',dept:'operations',c:'#e67e22',ic:'I',tags:['实习','深圳'],website:'https://insforge.dev',type:'实习',desc:`<h3>工作职责</h3><ul><li>负责InsForge在Twitter等海外平台的内容运营、社区建设与品牌传播</li><li>参与Twitter、YouTube、Reddit、LinkedIn等海外开发者渠道的内容运营与社区互动</li><li>跟进AI编程工具链前沿动态，围绕真实开发者工作流捕捉内容切口</li><li>输出与开发者画像高度匹配的内容，协助完成调研、竞品拆解</li></ul>
<h3>任职要求</h3><ul><li>CS背景或同等技术理解力，熟悉JavaScript、Next.js、React等主流技术栈，熟练使用GitHub</li><li>有使用Cursor、Claude Code、Codex等AI编程工具进行全栈开发的实际经验</li><li>对Twitter、Reddit、YouTube等海外开发者社区有真实使用习惯</li><li>能适应部分美西时间工作节奏</li><li>可保证连续3个月、每天8小时稳定投入</li></ul>
<h3>加分项</h3><ul><li>擅长海外meme玩梗</li></ul>`},
{id:'08b76cca',team:'Kuku',pos:'Product Designer',loc:'上海',locD:'上海',dept:'design',c:'#8e44ad',ic:'K',tags:['全职','上海'],website:null,type:'全职',desc:`<h3>工作职责</h3><ul><li>产品定义、交互设计、视觉体系的全链路</li><li>与CEO、产品、技术直接合作</li><li>设计将在1-2周内落地上线</li></ul>
<h3>任职要求</h3><ul><li>沉迷于苹果美学和iOS app设计，熟悉北美用户审美</li><li>相信设计是解决问题的方式，有打造世界级影响力产品的决心</li></ul>`},
{id:'987f33cb',team:'Kuku',pos:'AI Engineer',loc:'上海',locD:'上海',dept:'engineering',c:'#8e44ad',ic:'K',tags:['全职','实习','上海'],website:null,type:'全职',desc:`<h3>工作职责</h3><ul><li>负责从算法设计→开发→评估→产品落地的全链路</li><li>设计并实现多人关系记忆网络，构建Agentic AI行为系统</li></ul>
<h3>任职要求</h3><ul><li>对AI应用领域最新技术有极高好奇心和热情</li><li>对记忆之间的关联和关系状态网络感兴趣</li><li>至少2年开发AI应用的实战经验</li><li>熟悉agent memory和context engineering</li><li>熟悉LangGraph/CrewAI/Assistants等agent frameworks</li><li>熟悉LLM observability/evals（Langfuse/Promptfoo/Ragas/TruLens）</li></ul>`},
{id:'4d914cc8',team:'Kuku',pos:'Product Intern（产品实习生）',loc:'上海',locD:'上海',dept:'product',c:'#8e44ad',ic:'K',tags:['实习','上海'],website:null,type:'实习',desc:`<h3>工作职责</h3><ul><li>共创产品vision，负责0-1、1-2的产品构建</li><li>涵盖核心gamification loop流程设计、分享裂变增长功能点、主动式AI功能设计和记忆体系需求制定</li></ul>
<h3>任职要求</h3><ul><li>有野心，愿意打造有世界级影响力的产品</li><li>热衷体验北美最新2C产品，热爱GenZ文化，可以纯英文工作</li><li>对游戏化产品/分享裂变/AI记忆体系之一有超出常人的热情</li><li>有很强的沟通表达能力</li></ul>`},
{id:'876ed86c',team:'Skyris',pos:'ROS机器人开发工程师',loc:'深圳',locD:'深圳',dept:'engineering',c:'#1abc9c',ic:'S',tags:['全职','深圳'],website:'https://www.skyrisai.com',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责基于ROS/ROS2的机器人整体系统开发和模块整合</li><li>搭建与维护机器人控制框架（感知、建图、导航、运动控制等）</li><li>主导VSLAM/多传感器融合的视觉定位与建图方案</li><li>与硬件、结构、AI算法等团队协作，完成从原型到可交付产品的验证</li></ul>
<h3>任职要求</h3><ul><li>2~4年ROS/机器人系统开发经验，完成过实际工程项目</li><li>熟练掌握ROS/ROS2框架</li><li>有实际VSLAM/多传感器融合项目经验，熟悉ORB-SLAM/VINS/RTAB-Map等方案</li><li>熟悉视觉感知/IMU/激光雷达等软硬件接口调试与标定</li></ul>`},
{id:'fc1a41bc',team:'Skyris',pos:'硬件开发工程师',loc:'深圳',locD:'深圳',dept:'engineering',c:'#1abc9c',ic:'S',tags:['全职','深圳'],website:'https://www.skyrisai.com',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责产品硬件系统顶层设计和技术选型（主控、传感、驱动、通信、电源管理等）</li><li>主导高速电路、高精度模拟信号及FPC复杂硬件设计</li><li>负责EMC、SI/PI、热设计、安规和可靠性设计与优化</li><li>与AI软件、算法、机械结构、工业设计团队协同，主导软硬件接口定义</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，电子工程/通信工程/自动化相关专业</li><li>5年以上复杂嵌入式硬件产品开发经验，至少主导过一款产品从概念到量产全过程</li><li>精通高速数字电路设计和模拟电路设计，拥有丰富EMC/SI/PI调试经验</li><li>熟练使用Cadence/Allegro或Altium Designer进行8层及以上PCB设计</li></ul>
<h3>加分项</h3><ul><li>有机器人、无人机、智能家居、可穿戴设备硬件开发经验</li><li>有摄像头、麦克风阵列、电机驱动、电池管理系统开发经验</li><li>熟悉无线通信（Wi-Fi、Bluetooth）模块和射频基础知识</li></ul>`},
{id:'5731259e',team:'Skyris',pos:'嵌入式软件工程师',loc:'深圳',locD:'深圳',dept:'engineering',c:'#1abc9c',ic:'S',tags:['全职','深圳'],website:'https://www.skyrisai.com',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责机器人软件编写与维护（传感器驱动、电机驱动、控制器、网络协议栈等）</li><li>与不同部门沟通研发需求，确定最佳解决方案</li><li>参与产品可靠性分析、风险管理及失效评价分析</li></ul>
<h3>任职要求</h3><ul><li>全日制本科及以上，软件/电子/计算机相关专业</li><li>熟悉操作系统、网络协议栈、数据结构、数字信号处理</li><li>熟悉C语言及IIC、SPI、UART、USB等通讯接口</li><li>熟练使用Git版本管理工具和命令行</li></ul>
<h3>加分项</h3><ul><li>有从0到1完成过项目的经验</li><li>有音视频相关开发经验</li><li>有无人机飞控相关开发经验</li><li>开源项目维护者</li></ul>`},
{id:'1b35b16f',team:'Skyris',pos:'建模实习生',loc:'深圳',locD:'深圳',dept:'design',c:'#1abc9c',ic:'S',tags:['实习','深圳'],website:'https://www.skyrisai.com',type:'实习',desc:`<h3>工作职责</h3><ul><li>负责飞行机器人核心机械结构的3D建模、图纸绘制及技术文档输出</li><li>参与结构方案优化、材料选型及公差配合设计</li><li>配合完成样机制作、装配调试，解决生产及测试中的机械问题</li><li>熟练运用3D打印技术完成零件快速成型</li></ul>
<h3>任职要求</h3><ul><li>机器人、自动化相关专业，掌握机械原理、机械制图、公差配合等基础知识</li><li>熟悉至少一种工业级3D建模软件（SolidWorks/Fusion360等）</li><li>熟悉3D打印机操作及切片软件使用</li><li>熟练使用电钻、锯子、丝锥、游标卡尺等工具</li></ul>`},
{id:'99aa8a54',team:'Skyris',pos:'ROS机器人开发实习生',loc:'深圳',locD:'深圳',dept:'engineering',c:'#1abc9c',ic:'S',tags:['实习','深圳'],website:'https://www.skyrisai.com',type:'实习',desc:`<h3>工作职责</h3><ul><li>负责公司各类机器人系统软件开发与维护</li><li>主导机器人系统软件架构设计与模块化开发（感知、决策、控制、运动规划等）</li><li>参与多种机器人平台软件适配与集成开发</li><li>协助硬件团队进行软硬件联调，支持现场调试和产品化落地</li></ul>
<h3>任职要求</h3><ul><li>计算机科学/机器人技术/自动化/机械电子等相关专业本科及以上</li><li>熟练掌握C++/Python，至少2年ROS1/ROS2开发经验</li><li>熟悉Linux开发环境</li><li>熟悉常用仿真工具（Gazebo、mujoco、isaacsim等）</li></ul>
<h3>加分项</h3><ul><li>有机器人竞赛、科研或实际工程经验（AGV、AMR、服务机器人等）</li><li>有开源项目经验</li><li>有多机器人调度、SLAM、运动规划等开发经验</li></ul>`},
{id:'c9c05269',team:'SP1',pos:'交付/运营PM实习生（项目执行方向）',loc:'北京',locD:'北京',dept:'operations',c:'#c0392b',ic:'S',tags:['实习','北京'],website:null,type:'实习',desc:`<h3>工作职责</h3><ul><li>协助项目负责人推进项目落地，跟进时间节点与执行进度</li><li>对接设计、内容、展位、海外资源等外包方，整理需求与反馈</li><li>把零散信息整理成清晰的项目状态与下一步动作</li></ul>
<h3>任职要求</h3><ul><li>做事靠谱、细心，对时间节点敏感</li><li>能同时处理多件事</li><li>对项目型工作有兴趣，愿意承担责任</li></ul>`},
{id:'51c5e4ee',team:'SP1',pos:'财务运营实习生（Finance & Operations）',loc:'上海',locD:'上海',dept:'operations',c:'#c0392b',ic:'S',tags:['实习','上海'],website:null,type:'实习',desc:`<h3>工作职责</h3><ul><li>梳理跨项目资金结构，参与预算、现金流管理及决策模型维护</li><li>审核报销、核对合同/付款逻辑，在扩张前识别边界与风险</li><li>发票查验、收支对账、资料归档</li></ul>
<h3>任职要求</h3><ul><li>大四在读（财会专业），线下周均5天，持续3个月以上</li><li>熟练使用Excel/Google Sheets，能看懂基础报表</li><li>逻辑清晰，对数字敏感，保密意识强</li></ul>`},
{id:'9b5ecfb0',team:'SP1',pos:'研究与项目调研实习生',loc:'北京/上海',locD:'北京/上海',dept:'operations',c:'#c0392b',ic:'S',tags:['实习','北京/上海'],website:null,type:'实习',desc:`<h3>工作职责</h3><ul><li>主动触达来自黑客松、开源社区、校园项目的创作者，完成访谈整理</li><li>将访谈与观察转化为结构清晰的内容，参与社交媒体内容发布</li><li>通过行动验证逻辑，对结果负责</li></ul>
<h3>任职要求</h3><ul><li>强行动力，能自驱从0到1推进事情</li><li>有判断与表达直觉，能把复杂问题讲成60秒能懂的话</li><li>真实好奇心，对创业、新产品和趋势有主动研究习惯</li></ul>`},
{id:'7f06faee',team:'Tripo',pos:'品牌与市场负责人',loc:'杭州',locD:'杭州',dept:'operations',c:'#d35400',ic:'T',tags:['全职','Remote'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>定义并持续优化Tripo的品牌故事，统一所有渠道调性</li><li>提升在媒体、创作者社区、开发者生态及行业活动中的品牌声量</li><li>统筹PR、社媒及内容，把产品发布、社区动态转化为有影响力的品牌叙事</li><li>管理线上线下活动中的品牌呈现，强化Tripo辨识度</li></ul>
<h3>任职要求</h3><ul><li>6年以上品牌、市场或传播经验，科技/AI/开发者平台背景优先</li><li>有全球品牌建设经验，能将复杂技术讲清楚</li><li>能兼顾品牌调性、市场声量与业务目标，跨部门协同能力强</li></ul>
<h3>加分项</h3><ul><li>用过AI工具做内容</li><li>有从产品到平台的品牌升级经验</li><li>熟悉创作者或开发者生态</li></ul>`},
{id:'46ad1ae3',team:'Tripo',pos:'海外效果广告设计师（视频方向）',loc:'北京',locD:'北京',dept:'design',c:'#d35400',ic:'T',tags:['全职','北京'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责Facebook(Meta)、Google等平台投放广告素材的设计与制作</li><li>从选品、素材收集（录屏、BGM、文案）、剪辑到动效、配乐、口播全流程制作</li><li>了解海外社媒内容趋势，挖掘新广告创意</li><li>基于广告数据（CTR/CVR/CPA/ROI）持续迭代优化素材</li><li>配合投放团队快速产出多版本素材用于A/B测试</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，2年以上信息流广告素材制作经验</li><li>熟练掌握Photoshop/剪映/Illustrator/AE/PR</li><li>熟练使用Gemini/Nanobana/即梦/Kling/Veo3等AI生图生视频工具</li><li>具备良好的剪辑节奏感和视听语言审美</li><li>具备基础英语阅读能力</li></ul>
<p><strong>申请须知：</strong>必须提交个人作品集</p>`},
{id:'98548992',team:'Tripo',pos:'海外广告优化师',loc:'北京',locD:'北京',dept:'operations',c:'#d35400',ic:'T',tags:['全职','北京'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责公司AI产品在海外市场（Google、Meta等）的广告投放策略制定与执行</li><li>定期监控、分析、优化推广数据及核心KPI指标</li><li>对推广素材效果进行分析与沉淀，优化素材资源</li><li>定期调研市场与竞品动态</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，3年以上海外市场广告推广经验</li><li>熟悉Meta、Google、Bing等海外广告平台的特性、执行、数据复盘</li><li>具备较强的数据意识，能从数据中洞察可操作的推广策略</li><li>AI产品Web与App推广经验优先</li></ul>`},
{id:'5af2c950',team:'Tripo',pos:'达人营销',loc:'北京/杭州',locD:'北京/杭州',dept:'operations',c:'#d35400',ic:'T',tags:['全职','北京/杭州'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>聚焦TikTok/Instagram/YouTube等海外平台，挖掘评估潜在KOL，搭建高质量KOL资源库</li><li>负责KOL项目落地（推广Brief、样品寄送、内容跟进、转化效果追踪）</li><li>用英文独立沟通KOL，推进合作方案洽谈，维护长期合作关系</li><li>收集KOL内容表现与转化数据，定期输出复盘报告</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，市场营销相关专业优先，3年以上海外KOL营销经验</li><li>优秀的英文书面与口语能力，可独立与海外KOL商务谈判</li><li>熟悉TikTok/Instagram/YouTube机制与生态，网感强</li><li>对数据敏感，具备基础分析能力</li></ul>`},
{id:'36ecd200',team:'Tripo',pos:'Agent产品经理',loc:'杭州',locD:'杭州',dept:'product',c:'#d35400',ic:'T',tags:['全职','杭州'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>面向真实业务/用户场景进行AI Agent产品规划与需求拆解，制定Agent Roadmap</li><li>将业务问题抽象为Agent结构，定义角色分工、技能边界与可衡量指标</li><li>设计链式/并行Agent工作流，构建Prompt规范、记忆、外部工具调用策略</li><li>设计评测人机协同策略，对Agent进行持续性能优化</li><li>推动Agent在真实环境上线与复用扩散，与运营/销售/客户成功协同</li></ul>
<h3>任职要求</h3><ul><li>理解大模型基本工作机制和主流增强策略，理解幻觉/漂移/不确定性产生机制</li><li>熟悉主流模型生态（GPT/Qwen/Gemini/Claude/Llama）成本/安全上的差异</li><li>理解Prompt结构化设计底层逻辑</li><li>3年以上RPA/自动化/AI工具类产品经验（或Agent实战经验）</li><li>有真实Agent上线案例，并能给出评估指标</li></ul>`},
{id:'3a593723',team:'Tripo',pos:'商业化产品经理',loc:'北京/杭州',locD:'北京/杭州',dept:'product',c:'#d35400',ic:'T',tags:['全职','北京/杭州'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>设计并优化订阅、按量付费、权益组合等商业化模式</li><li>用价格实验、权益打包、触发时机优化提升付费率和续费率</li><li>挖掘不同用户群体的价值潜力，推动付费用户转化与升级</li><li>用数据驱动商业化决策，盯紧付费率、ARPPU、LTV、ROI</li></ul>
<h3>任职要求</h3><ul><li>3年以上商业化/变现产品经验（工具类、SaaS、AI产品加分）</li><li>有完整推动营收增长的成功案例</li><li>熟悉订阅制、按量付费、增值权益等商业模式</li><li>有海外商业化经验、熟悉国际支付体系优先</li></ul>`},
{id:'9d87a9b7',team:'Tripo',pos:'商业化产品运营经理',loc:'北京/杭州',locD:'北京/杭州',dept:'operations',c:'#d35400',ic:'T',tags:['全职','北京/杭州'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责核心指标：付费转化率和留存率，设计执行用户生命周期运营</li><li>打造清晰有吸引力的产品功能、定价层级与差异化信息，确保各渠道一致性</li><li>与产品及管理层合作，优化定价结构与增销机会</li><li>管理并优化FAQ、帮助中心、上手指南、视频教程等，降低使用门槛</li><li>与数据分析团队协作，监测转化漏斗、流失原因和用户LTV</li></ul>
<h3>任职要求</h3><ul><li>3年以上产品运营/增长运营/商业化或相关经验</li><li>熟悉数据分析、转化漏斗指标和实验方法（A/B、多变量测试）</li><li>具备较好的逻辑思维和深入思考能力</li></ul>`},
{id:'e1e0ae7f',team:'Tripo',pos:'前端开发工程师',loc:'北京/杭州',locD:'北京/杭州',dept:'engineering',c:'#d35400',ic:'T',tags:['全职','北京/杭州'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>负责Tripo核心渲染引擎与交互系统构建</li><li>基于WebGL/WebGPU优化3D查看器/编辑器，保障大规模场景FPS 60+</li><li>打造全球站（SaaS）前端架构，构建极致流畅的复杂交互界面</li><li>探索AI+前端技术（WebAssembly、端侧AI推理）</li></ul>
<h3>任职要求</h3><ul><li>精通JS/TS，深度掌握React/Vue框架原理</li><li>追求像素级UI还原，具备高可维护组件库开发能力</li><li>熟悉Three.js/Babylon.js/WebGL，掌握渲染管线、GLSL等（核心加分项）</li></ul>`},
{id:'2b58f133',team:'Tripo',pos:'后端开发工程师',loc:'北京',locD:'北京',dept:'engineering',c:'#d35400',ic:'T',tags:['全职','北京'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>主导全球化高可用架构，解决跨国链路、高并发、数据一致性问题</li><li>设计3D大模型推理算力调度系统，平衡成本与性能</li><li>支撑业务指数级增长，保障SLA 99.9%服务稳定性</li></ul>
<h3>任职要求</h3><ul><li>精通Go/Python/Java任一语言，精通分布式、微服务、向量数据库等</li><li>具备高并发系统实战经验，熟练使用K8s、Docker、云服务平台</li></ul>`},
{id:'a607551c',team:'Tripo',pos:'HRBP（偏招聘）',loc:'杭州',locD:'杭州',dept:'operations',c:'#d35400',ic:'T',tags:['全职','杭州'],website:'https://www.tripo3d.ai/zh',type:'全职',desc:`<h3>工作职责</h3><ul><li>根据公司年度业务规划制定并执行招聘计划，持续优化招聘渠道与策略</li><li>负责端到端招聘流程管理（职位发布、简历筛选、面试协调、背调、录用沟通）</li><li>作为HRBP深入理解业务战略，在组织发展、团队建设、绩效管理等方面提供解决方案</li><li>利用数据分析驱动招聘与人才决策</li></ul>
<h3>任职要求</h3><ul><li>本科及以上，人力资源管理/心理学/工商管理等相关专业优先</li><li>3年以上招聘相关工作经验，互联网/科技/金融行业或HRBP经验优先</li><li>具备较强的数据分析能力和业务洞察力</li><li>英语可作为工作语言，能流畅进行书面与口语沟通</li></ul>`},
{id:'99998a30',team:'万物时',pos:'AI Agent算法实习生（软硬协同方向）',loc:'杭州',locD:'杭州',dept:'engineering',c:'#5b2c6f',ic:'万',tags:['实习','杭州'],website:null,type:'实习',desc:`<h3>工作职责</h3><ul><li>为核心IP构建具备记忆、性格与感知能力的AI Agent架构</li><li>将Agent的决策与情绪精准映射并触发硬件端的3D角色动作与日常动画表现</li><li>配合团队打通「云端大模型-本地Linux硬件-动画渲染」的完整交互链路</li></ul>
<h3>任职要求</h3><ul><li>玩过且熟悉OpenClaw、OpenInterpreter等开源Agent框架，有实际搭过智能体的经历</li><li>Python扎实，能快速看懂、跑通并魔改GitHub上的前沿AI开源项目</li><li>具备超强的学习力与成长性，喜欢硬核折腾</li></ul>
<h3>加分项</h3><ul><li>玩过树莓派/开发板/Linux</li><li>了解游戏/动画的状态机（State Machine）逻辑</li></ul>`},
];

const _AC=['#7eb8da','#d4a0a0','#a8c686','#d4b896','#b0a0d4','#86b8c6','#c6a086','#a0b8d4','#c6c686','#d496b8','#96c6b8','#c68686','#86a8c6','#b8c6a0','#c6a0c6'];
const _AI=['JK','AL','MR','SC','TP','RW','LD','KN','BF','HG','QZ','VX','YM','ED','OP'];
function makeAv(seed){return '<div class="av" style="background:'+_AC[seed%_AC.length]+'">'+_AI[seed%_AI.length]+'</div>';}
const extSvg='<svg class="xi" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M7 17 17 7M7 7h10v10"/></svg>';
const extSvgSm='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" style="width:12px;height:12px;color:#b0b0b0"><path d="M7 17 17 7M7 7h10v10"/></svg>';
